# Generated by Django 6.0.1 on 2026-02-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Photo',
            new_name='Profile',
        ),
    ]
