# Generated by Django 6.0.1 on 2026-02-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_photo_employee_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Contact',
        ),
        migrations.AlterField(
            model_name='employee',
            name='Profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
